version: '3.0'
services:

  shopware5_web:
    image: proudcommerce/docker-php73-apache-stretch
    volumes:
      - ./web/www/:/var/www/html/:cached
      - ./web/logs/:/var/log/apache2/
    env_file:
      - app.env
    depends_on:
      - shopware5_mysql
    ports:
      - "8080:80"
            
  shopware5_mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql
    env_file:
      - app.env
      - db.env
    ports:
      - "3306:3306"
      
  shopware5_mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  shopware5_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: shopware5_mysql
